services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - './config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './data/mosquitto:/mosquitto/data'
      - './data/mosquitto/log:/mosquitto/log'
    networks:
      - default
  influxdb:
    image: 'influxdb:2'
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ttfoley
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: mush
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./config/influxdb:/etc/influxdb2
      
  telegraf:
    image: 'telegraf:latest'
    container_name: telegraf
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./config/telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: "root:root"
    depends_on:
      - influxdb

  led_control:
    build: 
      context: ../control/led_control
      dockerfile: Dockerfile
    container_name: led_control
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    networks:
      - default
    environment:
      - PYTHONBUFFERED=1
  
  temperature_driver:
    build: 
      context: ../control
      dockerfile: temperature_driver/Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - PYTHONUNBUFFERED=1
      - IN_DOCKER=1
    container_name: temperature_driver
    depends_on:
      - mosquitto
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
