# Enhanced Configuration for Microcontroller c1
# This shows what the config should look like to generate the full autogen_config.h

# Basic device info
device_id: "c1"
description: "Sensor controller for fruiting chamber"

# WiFi Configuration (temporarily using actual values for testing)
wifi:
  ssid: "ThomassenCondo_EXT"
  password: "OceanBreeze"

# MQTT Configuration (temporarily using actual values for testing)
mqtt:
  broker_address: "192.168.1.17"
  broker_port: 1883
  username: "ttfoley"
  password: "password"
  client_id: "controller1"

# NTP Configuration
ntp:
  address: "us.pool.ntp.org"
  utc_offset_seconds: 0
  update_interval_ms: 3600000

# FSM Configuration
fsm:
  states:
    - SETUP_HW
    - CONNECT_WIFI  
    - SYNC_NTP
    - CONNECT_MQTT
    - PUBLISH_BOOT_STATUS
    - PROCESS_COMMANDS
    - READ_SENSORS
    - PUBLISH_DATA
    - OPERATIONAL_PERIODIC_CHECKS
    - WAIT
    - RESTART

# Comprehensive Timing Constants
timing:
  # Basic intervals
  publish_interval_ms: 15000
  sensor_and_status_publish_interval_ms: 30000
  status_publish_interval_ms: 300000
  
  # Connection timeouts
  wifi_connect_timeout_ms: 30000
  mqtt_connect_timeout_ms: 20000
  ntp_sync_timeout_ms: 15000
  
  # FSM retry configuration
  max_wifi_attempts: 10
  wifi_attempt_timeout_ms: 20000
  max_ntp_attempts: 5
  ntp_attempt_timeout_ms: 30000
  
  # Operation timeouts
  max_time_no_publish_ms: 300000
  maintenance_restart_interval_ms: 604800000  # 1 week
  periodic_checks_interval_ms: 3600000        # 1 hour
  
  # Loop and retry delays
  mqtt_retry_delay_ms: 2000
  restart_delay_ms: 1000
  main_loop_delay_ms: 10
  ntp_loop_update_interval_ms: 60000
  debug_queue_interval_ms: 30000

# I2C Bus Configuration
i2c:
  sda_pin: 21
  scl_pin: 22

# I2C Sensor Configurations with full struct data
i2c_sensors:
  - type: "SHT85"
    instance_name: "SHT85_0"
    address: 0x44
    point_name: "FruitingChamber_SHT85_0"
    temperature_uuid: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
    humidity_uuid: "9c8b1da3-1b2a-4c8e-9d1f-6a7b8c9d0e1f"
    c_to_f: true
    
  - type: "BME280"
    instance_name: "BME280_1" 
    address: 0x77
    point_name: "FruitingChamber_BME280_1"
    temperature_uuid: "c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f"
    humidity_uuid: "d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f70"
    pressure_uuid: "e4f5a6b7-c8d9-4e0f-1a2b-3c4d5e6f7081"
    c_to_f: true

# DHT Sensor Configuration
dht_sensors:
  - type: "DHT22"
    instance_name: "DHT22_0"
    pin: 27
    point_name: "Outside_DHT22_0"
    temperature_uuid: "2a3b4c5d-6e7f-4a1b-8c2d-3e4f5a6b7c8d"
    humidity_uuid: "b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"
    c_to_f: true

# OneWire Sensor Configuration  
onewire_sensors:
  - type: "DS18B20"
    instance_name: "DS18B20_0"
    pin: 32
    point_name: "FruitingChamber_DS18B20_0"
    temperature_uuid: "f5a6b7c8-d9e0-4f1a-2b3c-4d5e6f708192"
    resolution_bits: 10
    c_to_f: true
    
  - type: "DS18B20"
    instance_name: "DS18B20_1"
    pin: 33
    point_name: "FruitingChamber_DS18B20_1" 
    temperature_uuid: "06b7c8d9-e0f1-4a2b-3c4d-5e6f708192a3"
    resolution_bits: 10
    c_to_f: true

# System Status Points
status_points:
  wifi_uptime:
    point_name: "C1_WifiUptime"
    uuid: "17c8d9e0-f1a2-4b3c-4d5e-6f708192a3b4"
    topic: "mush/c1/statuses/wifi_uptime"
    
  last_restart_reason:
    point_name: "C1_LastRestartReason" 
    uuid: "28d9e0f1-a2b3-4c4d-5e6f-708192a3b4c5"
    topic: "mush/c1/statuses/last_restart_reason"

# Debug Configuration
debug:
  i2c_scan_on_startup: true

