# Configuration for Microcontroller c2
# Path: control/config/microcontrollers/c2_config.yaml
# Conforms to the MicrocontrollerConfig Pydantic model

# C2 is primarily an actuator controller.
# It does not have I2C, DHT, or OneWire sensors listed in its points_provided.
# If it did, those sections (i2c, i2c_devices, dht_sensors, onewire_devices) would be included here.

# Digital Outputs for actuators controlled by C2
digital_outputs:
  - pin: 25 # 
    name: "HumidifierRelay" # Optional logical name
    # This is the COMMAND Point UUID that c2 listens to for this actuator
    point_uuid: "6c21f1a2-b3c4-4d5e-6f70-8192a3b4c5d7" # C2_CP25_Humidifier_Command
    initial_state: "off"

  - pin: 26 # 
    name: "HeatingPadRelay" # Optional logical name
    point_uuid: "8e43f1a2-b3c4-4d5e-6f70-8192a3b4c5d9" # C2_CP26_HeatingPad_Command
    initial_state: "off"

  - pin: 32 # 
    name: "LightRelay" # Optional logical name
    point_uuid: "a065f1a2-b3c4-4d5e-6f70-8192a3b4c5db" # C2_CP32_Light_Command
    initial_state: "off"

  - pin: 33 # 
    name: "VentFanRelay" # Optional logical name
    point_uuid: "c287f1a2-b3c4-4d5e-6f70-8192a3b4c5dd" # C2_CP33_VentFan_Command
    initial_state: "off"

  - pin: 4  # 
    name: "StatusLED" # Optional logical name
    point_uuid: "e4a9f1a2-b3c4-4d5e-6f70-8192a3b4c5df" # C2_LED1_StatusLED_Command
    initial_state: "off"

# Timing Parameters for C2
publish_frequency_ms: 15000 # Example: publish sensor data (like WifiUptime) every 15 seconds
output_republish_frequency_ms: 60000 # Example: republish actuator statuses every 60 seconds

