# Configuration for Microcontroller c3
# Path: control/config/microcontrollers/c3_config.yaml
# Conforms to the MicrocontrollerConfig Pydantic model

# I2C Bus Configuration (for SCD4x sensor)
# PLEASE UPDATE sda_pin and scl_pin to your ESP32's actual I2C pins for c3.
i2c:
  sda_pin: 21 # Example I2C SDA pin
  scl_pin: 22 # Example I2C SCL pin
  # clock_speed: 100000 # Optional, Sensirion sensors often prefer 100kHz

i2c_devices:
  - sensor_model: "SCD41" # Assuming SCD4x is an SCD41, adjust if different (e.g., SCD40)
    address: 0x62        # PLEASE VERIFY: Default I2C address for SCD4x sensors
    point_uuids:
      co2: "f5baf1a2-b3c4-4d5e-6f70-8192a3b4c5e0"         # C3_SCD4x_CO2
      temperature: "06cbf1a2-b3c4-4d5e-6f70-8192a3b4c5e1" # C3_SCD4x_Temperature
      humidity: "17dcf1a2-b3c4-4d5e-6f70-8192a3b4c5e2"    # C3_SCD4x_Humidity
    settings: # Optional device-specific settings for SCD4x
      automatic_self_calibration: false # Example: if you want to disable ASC
      # altitude_compensation: 0 # Example: altitude in meters if needed

# C3 does not have DHT, OneWire, or Digital Outputs listed in its points_provided.
# dht_sensors: []
# onewire_devices: []
# digital_outputs: []

# Timing Parameters for C3
publish_frequency_ms: 30000 # Example: publish sensor data every 30 seconds (SCD4x can be slower)
# output_republish_frequency_ms: 60000 # Not relevant as C3 has no digital_outputs defined

